### ISSUE TITLE
Plan: Browser View

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#125]
The browser-based view complements the v1 Webmaker app on Android. It enables project shares to be viewed by non-Android users, on desktop or mobile.

Tasks fall into a few groups:  
- [ ] build container UI (https://github.com/mozilla/webmaker-desktop/issues/57#issuecomment-112847186)
- [ ] prep app components for use in-browser (#108)
- [ ] build touch handling in JS
- [ ] test cross-browser (#124)
- [ ] route Android users
  - [x] to app if installed (#69)
  - [ ]  to play store if app not installed (#62)

Let's drop more details into this meta ticket and then file issues accordingly. 

cc @simonwex @thisandagain

**Comment by xmatthewx** [comment]
@k88hudson @gvn @Pomax - Please review the list above today and let me know if there are any big gaps. We're trying to make sure we have enough resources to handle this post-Whistler.

**Comment by xmatthewx** [comment]
tracking in #154
