### ISSUE TITLE
Build browser-based player

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#154]
- [x] in-browser wrapper (migrate webmaker-browser to use core)
- [x] project view (DE-SCOPED)
  - tap to open page
  - pan
  - pinch-zoom for android only, browsers tap to zoom
- [ ] page view
  - [x] show page view by default
  - [x] render neighbors
  - [x] reduce opacity on neighbors
  - page to page nav buttons (TO FILE)
  - disable swipe (TO FILE)
  - [x] page size fit to viewport, margins (see http://codepen.io/k88hudson/pen/YXvYZm)
- [x] get the app cta (TO FILE)
  - landscape browsers only
  - dismiss and stay dismissed
- [x] refactor page rendering for thumbnail sevice
- [x] localization
- [ ] analytics https://github.com/mozilla/webmaker-core/issues/313
- [ ] QA https://github.com/mozilla/webmaker-core/issues/16#issuecomment-122038905

UI & UX discussion in #57

**Comment by xmatthewx** [comment]
### Project viewer

![project-viewer](https://cloud.githubusercontent.com/assets/53411/8630069/855c9e9c-272f-11e5-8d75-18e5c85091a2.png)

**Comment by xmatthewx** [comment]
### Page viewer

![page-viewer](https://cloud.githubusercontent.com/assets/53411/8599829/9b7e4f5e-2630-11e5-84cb-d7f5e21b57f7.png)

**Comment by gvn** [comment]
@flukeout can you link the comps in this ticket?

**Comment by gvn** [comment]
See also: https://github.com/mozilla/webmaker-browser/issues/57#issuecomment-120540769

**Comment by flukeout** [comment]
@vazquez Has all of the originals

**Comment by vazquez** [comment]
Sketch file available here: https://drive.google.com/open?id=0ByIoeeW0a3R_WXZsbW51OS1rdTQ

**Comment by flukeout** [comment]
Here's a generic spec for when to show the 'arrow' vs the 'semicircle' indicator.

@gvn Let me know if this is clear and helpful! Applies to arrows in all directions.

![image](https://cloud.githubusercontent.com/assets/25212/8686967/18045204-2a40-11e5-999d-95b0e69f61d8.png)

**Comment by flukeout** [comment]
Here's a positioning guide for the zoom out icon. Let me know if you'd rather have this (and the above) behaviour demonstrated in codepen or something like that.

![image](https://cloud.githubusercontent.com/assets/25212/8687772/71b3833a-2a48-11e5-881a-a77cc6f18a03.png)

**Comment by xmatthewx** [comment]
Browser-based viewer built. File new issues as needed.
