### ISSUE TITLE
Milestone: Build unified prototype for desktop/tablet

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#2]
This is the meta ticket for the Desktop/tablet prototype based on planning in https://github.com/MozillaFoundation/plan/issues/365

Our work on Tiles hints toward a new Webmaker, a compelling platform that's both webby and different from other existing channels for making and sharing. This heartbeat aims to design the features and complete a coherent look at this new tool, the new Webmaker.
### Audience
- Primary addressable audience: Firefox users on desktop and Android
- Users on Webmaker who want to create content
- People who view content on Webmaker
### Success :v:

**Primary** - Articulate a complete experience for both viewers and creators, to discover, share, and make on Webmaker, with parity across mobile and desktop/tablet.

**Secondary** - Design an editor that hints at the underlying technology. (May differ for authors on desktop and mobile.)
### Vision

If Webmaker was a polaroid, the end of this heartbeat would be the moment _other people_ could grok the whole image despite the fuzzy corners. To achieve this:
- Define _key_ features and their use (sorry text shadow). Each feature should be necessary or high value.
- Better emphasize the inherent flexibility enabled by moving and linking tiles.
- Identify ways to clarify the zoom nav metaphor (ex: view transitions, ambient indicators).
### Scope

in scope
- gallery
- viewing (start flag)
- making
- element properties (text, image, button, my-code™)
- attribute editor (simple & advanced layers)
- share to gallery (public/private)
- jiggles

out of scope :do_not_litter: 
- onboarding
- profile
- animation
- social
### Deliverables :package:
- Unifying reference doc 
- InVision or similar prototype
- Annotation on interactions and transitions
- Nice to have: Working prototype to demo author navigation on mobile  
### Links :fist:
- planning - https://github.com/MozillaFoundation/plan/issues/365
- inVision - http://invis.io/PA2CNPOYG
- gSlides - https://docs.google.com/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit?usp=sharing

cc: @flukeout @sabrinang @thisandagain @cassiemc

**Comment by xmatthewx** [comment]
Anyone interested in following the design process can view our [live notebook](https://www.dropbox.com/s/lqwsf16dtrkarpi/Screenshot%202015-03-05%2013.22.29.png?dl=0), an experiment for remote collaboration. All the content is:
- a work in progress
- rough around the edges
- likely to evolve or pivot 

<a href="https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c2312ad6_19">![screenshot 2015-03-05 13 22 29](https://cloud.githubusercontent.com/assets/53411/6512229/280adda6-c340-11e4-9bfb-9b689bc24256.png)</a>

**Comment by xmatthewx** [comment]
Views for unified prototypes (mobile / desktop). 

Do: include essential states (ex: tile editor: empty vs element selected). 
Do: keep segments consistent.
Don't: detail multiple options to do a task (trust your gut and future tests and iterations).
- [x] Platform #3
  - switch between gallery, user, make views
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c2312ad6_19)
- [ ] Play experience
  - open a gallery item. nav between aerial view, tile view, and back  
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c52d193c_2127)
- [x] Tile editor #4 
  - add, move, and resize, and deselect an item  
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c2312ad6_113)
- [x] Element editor (image, text)
  - edit an image's properties, edit text properties
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c2312ad6_105)
- [x] Button linking #7
  - add a button, change its style, choose a target 
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c2312ad6_1026)
- [x] Aerial editor
  - add, move, edit, and remove tiles
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c52d193c_253)
- [x] Project settings
  - name a project, set start tile, share to gallery, exit
  - [notebook](https://docs.google.com/a/mozillafoundation.org/presentation/d/1-qXV4jbk3plbbXkjjerqvDyUCrCepGFDRGUM1g5XiHg/edit#slide=id.g8c52d193c_21)

Add WIP screenshots to the notebook. 

---

Round 2 if round 1 is done 
- [ ] Code hints & access
- [ ] Shared tiles
- [ ] Gallery favorites
- [ ] ...

**Comment by xmatthewx** [comment]
@flukeout @sabrinang 

We made some good progress this week. Next week, I'd like to switch gears:
1. put a hold a new ideas & explorations
2. nail down a single best guess wire for every mvp view
3. after that's done, resume debate on the details and alternatives

Our goal is to communicate everything floating in our minds, prototypes and sketches so that a growing circle of people can understand the project and contribute. After we do that, we can continue to iterate on features and interactions. 

Sound like a plan?

![tile editor](https://cloud.githubusercontent.com/assets/53411/6538688/5f2bd2f6-c433-11e4-9d2f-98c56a37763f.png)

We have [7 stories](https://github.com/mozilla/webmaker-desktop/issues/2#issuecomment-77436765) to tell like this by next Wed, to make clickable on Thurs, and share on Friday.

**Comment by xmatthewx** [comment]
@flukeout @sabrinang produced a comprehensive view of the tool. Great work!
- Mobile Prototype - http://invis.io/HZ2F7KDFA
- Tablet Prototype - Done-ish! http://invis.io/HE2FK9JTP
- Design Notebook - http://bit.ly/1FI5LFM

To wrap up today and Monday:
- [x] **Start flag** - Make a hamburgerless best guess for how to integrate this
- [ ] **Project details** - Add a gallery/make view almost identical to the hamburger drawer, hold the onions and hamburger. 
- [x] **Zoom** - Remove the zoom guide. Replace with tools at both aerial and tile view

Lastly:
- [ ] **Notebook** - Add these adjustments and other key screens and notes. Archive interesting bits, delete the noise.

**Comment by xmatthewx** [comment]
Revised mobile prototype. Nicely integrated sharing, better zoom, and consistent toolbar. :dart: 

http://invis.io/8X2GM9GDN

**Comment by xmatthewx** [comment]
Closing. 
- Plan for next steps: https://github.com/MozillaFoundation/plan/issues/377
- Tracking specific issues here in the [Unified UI milestone](https://github.com/mozilla/webmaker-desktop/milestones/Unified%20UI)
