### ISSUE TITLE
Transition new Webmaker.org site

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-desktop#75]
The current webmaker.org site will be retired and replaced with the new build in progress at beta.webmaker.org. We need to review the current site to make sure nothing gets lost in the shuffle.

**Comment by xmatthewx** [comment]
Things to consider: https://docs.google.com/document/d/1J6dkGIKesLNitsnYDz6NuA7UQYetmA3R9eSwHWE4iZE/edit

**Comment by thisandagain** [comment]
@xmatthewx Could you open up the sharing permissions on that doc?

**Comment by xmatthewx** [comment]
Should be good now. Doc is a WIP. Friday or Monday we can review and file issues.

**Comment by thisandagain** [comment]
Great! Thanks @xmatthewx . Let's do Monday so we can stay heads-down on Friday.

**Comment by xmatthewx** [comment]
Phase 1 - pre-Whistler
 - redirect from Webmaker.org home to beta (en-US only)
 - add new terms page and redirect to it

Phase 2 - post-Whistler
 - localize beta site
 - archive webmaker.org to old.webmaker.org
 - launch new Webmaker.org

cc @simonwex @jbuck

**Comment by secretrobotron** [comment]
From a chat with @gvn @cadecairos:

#### Questions
* Why are we archiving anything? Can we remove old content as opposed to storing it at old.webmaker.org?
  * If we're not maintaining the old stuff, we should have a deprecation notice.
* When is this transition happening?

#### Probable tasks
* Rename `webmaker-desktop` repo. Again.
* Port current MakeAPI content to postgres DB so people can look up their old stuff
* Re-hookup gallery page to postgres DB somehow

cc @simonwex @jbuck

**Comment by xmatthewx** [comment]
Excellent. This is a good step toward understanding the scope, timing and risks. 

> why archive?
1. Someone mentioned that translators and contributors like to grab screenshots of their work. 
2. We can allow [some content](https://webmaker.org/en-US/private-eye) to fade instead of investing time to migrate or deprecate

I think that an archive with a few redirects could reduce the risk and comms hassles, without significantly increasing the work. 

Other notes: 
https://docs.google.com/document/d/1J6dkGIKesLNitsnYDz6NuA7UQYetmA3R9eSwHWE4iZE/edit

**Comment by xmatthewx** [comment]
- [ ] post new legal terms #152

**Comment by mmmavis** [comment]
:shipit: :shipit: :shipit: :shipit: 

### Webmaker site launch
- Snippet starts July 27
- Site launched, tested, fixed by July 22

### Webmaker.org Redirects `ops`
- [ ] continue existing redirects on wm.org #177
- [ ] review logs, add new redirects, retire incoming links  https://github.com/mozilla/webmaker.org/issues/1423
- [ ] prep makes tool for domain switcheroo https://github.com/mozilla/id.webmaker.org/issues/339
- [ ] redirect beta project URLs to new permalinks #196

### Security `ops`
- [x] SSL Certificate updates https://github.com/mozilla/webmaker.org/issues/1425
  - `beta.webmaker.org` -> `webmaker.org` 
  - `webmaker.org` -> `old.webmaker.org`
- [x] Security Review #180

### Archive `ops`
- [x] archive current webmaker.org to old.webmaker.org https://github.com/mozilla/webmaker.org/issues/1424
- [ ] fix page loading https://github.com/mozilla/webmaker.org/issues/1428

---

### Localize
- [ ] localize anything that hasn't been localized #181

### Footer
- [x] add thimble/goggles link to footer https://github.com/mozilla/webmaker-core/issues/303

### Pages
- [ ] deal with /#/ in URL for  `/#/privacy` and `/#/legal` ?? ~~#172~~ https://github.com/mozilla/webmaker-browser/issues/182
- [ ] legal - update copy https://github.com/mozilla/webmaker-core/issues/442
- [ ] 404 https://github.com/mozilla/webmaker-browser/issues/70

### Social
- [ ] `p2` header links to share a link to webmaker.org via facebook etc useful for FF traffic #32

---

## QA
- [ ] test it #171

## Launch
- [ ] update link to new terms https://github.com/mozilla/webmaker-browser/issues/192

**Comment by mmmavis** [comment]
will create separate tickets after the above giant list has been looked over

**Comment by xmatthewx** [comment]
Cleaned up the list above based on things already completed. LInked/filed to a few specific issues. Let's file the rest of the details tomorrow and get feedback from @jbuck

**Comment by mmmavis** [comment]
wooohoooooo thanks @xmatthewx for making my terrifying list digestible :+1:

**Comment by jbuck** [comment]
:clap: 

Some comments:

> continue existing redirects on wm.org (TO FILE)

The existing redirects can be found in https://github.com/mozilla/webmaker.org/blob/a5c8b8eb18a3e6e494443f41bee33d11602344dd/routes/redirect.js

>  SSL Certificate updates 

The only ticket to file here as a prerequisite to both is adding old.webmaker.org to our current certificate

**Comment by xmatthewx** [comment]
I've revised the [site launch list above](https://github.com/mozilla/webmaker.org/issues/1423) and filed related issues. Everyone should look this over to make sure we don't break everything. @ldecoursy @hannahkane @secretrobotron @simonwex @jbuck @cadecairos
